/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    ConfidenceBadge: typeof import('./src/components/ConfidenceBadge.vue')['default']
    DataQualityBadge: typeof import('./src/components/DataQualityBadge.vue')['default']
    DiscoveryLeadCard: typeof import('./src/components/DiscoveryLeadCard.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    GlobalLocationSearch: typeof import('./src/components/GlobalLocationSearch.vue')['default']
    GlobalSearchBar: typeof import('./src/components/GlobalSearchBar.vue')['default']
    LeadCard: typeof import('./src/components/LeadCard.vue')['default']
    LoadingCard: typeof import('./src/components/LoadingCard.vue')['default']
    LocationMatchBadge: typeof import('./src/components/LocationMatchBadge.vue')['default']
    MobileHeader: typeof import('./src/components/MobileHeader.vue')['default']
    NextBestAction: typeof import('./src/components/NextBestAction.vue')['default']
    OpportunityScore: typeof import('./src/components/OpportunityScore.vue')['default']
    PropertyVisual: typeof import('./src/components/PropertyVisual.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SatelliteImagePanel: typeof import('./src/components/SatelliteImagePanel.vue')['default']
    SignalChip: typeof import('./src/components/SignalChip.vue')['default']
    StreetViewPanel: typeof import('./src/components/StreetViewPanel.vue')['default']
    WhaleBadge: typeof import('./src/components/WhaleBadge.vue')['default']
    WhaleHunterWorkspace: typeof import('./src/components/WhaleHunterWorkspace.vue')['default']
  }
}
